# These are supported funding model platforms

github: amandeepmittal

trigger:
- seu-branch

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Instalar o Node.js'

- script: |
    # Instalar as dependências
    npm install

    # Executar os testes
    npm test
  displayName: 'Construir e Testar'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
  displayName: 'Arquivar Artefatos'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    artifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publicar Artefatos'
- task: NodeTool@0
  inputs:
    versionSource: 'spec'
    versionSpec: '6.x'
